version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: fruits_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fruitsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - fruitsdb-data:/var/lib/mysql

volumes:
  fruitsdb-data: